# Ravi Bhikhie
# Euler Project
#
# Problem 002
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#  find the sum of the even-valued terms.

fib_seq = [1, 2, 0]
limit = 4000000
even_terms = []

while fib_seq[2] < limit:
    fib_seq[2] = fib_seq[1] + fib_seq[0]

    if (fib_seq[2] < limit ) and (fib_seq[2] % 2 == 0):
        even_terms.append(fib_seq[2])
        print "Added term %d" % fib_seq[2]

    fib_seq[0] = fib_seq[1]
    fib_seq[1] = fib_seq[2]

result = sum(even_terms)
print "Result: %d" % result

#sloppy, need to add 2.


